name: Publish to TabooLib Repository

on:
  push:
    branches: [ master ] 

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17' 
      - name: Setup Gradle
        uses: gradle/actions-setup-gradle@v3
        
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Publish with Gradle
        run: ./gradlew publish
        env:
          taboolibUsername: ${{ secrets.TABOOLIB_USERNAME }}
          taboolibPassword: ${{ secrets.TABOOLIB_PASSWORD }} 